### ISSUE TITLE
[Feature Request]: Додайте, будь ласка, підтримку української мови/Добавьте, пожалуйста, поддержку украинского языка

### ISSUE THREAD

**Issue by RomanVale71** [SuperZombi/HDrezka-downloader#2]
Спасибі Вам за розширення. Але б дуже хотілось, щоб Ви додали підтримку української мови. Я вже переклав Ваш файл messages.json і прикріпляю його нижче. Ще раз дякую.

Спасибо Вам за расширение. Но очень бы хотелось, чтобы Вы добавили поддержку украинского языка. Я уже перевел Ваш файл messages.json и прикрепляю его ниже. Еще раз спасибо.

[uk.zip](https://github.com/SuperZombi/HDrezka-downloader/files/8822950/uk.zip)

**Comment by SuperZombi** [comment]
Дякую. Додам ближчим часом (зараз сессiя)

**Comment by SuperZombi** [comment]
@RomanVale71, можна поцікавитися, як ви знайшли моє розширення?
