### ISSUE TITLE
Добавьте поддержку страницы http://hdrezka.me

### ISSUE THREAD

**Issue by RuslanBerkaz** [SuperZombi/HDrezka-downloader#3]
Добавьте, пожалуйста, поддержку страницы [http://hdrezka.me](https://t.co/4qPsp8Z11q), так как она является альтернативным адресом ресурса.

![2022-06-05_21-54](https://user-images.githubusercontent.com/106928808/172066450-ea58f859-3869-475b-9c45-545ff524aead.png)

![2022-06-05_21-55](https://user-images.githubusercontent.com/106928808/172066454-19e41704-5fc1-4a84-aa6f-708f4c5064eb.png)

**Comment by SuperZombi** [comment]
Добавил. Обновитесь https://github.com/SuperZombi/HDrezka-downloader/releases

**Comment by SuperZombi** [comment]
@RuslanBerkaz, можно поинтересоваться, как вы нашли мое расширение?
