### ISSUE TITLE
Возможность скачивать фильм или сериал сразу с несколькими озвучками

### ISSUE THREAD

**Issue by RedebMar** [SuperZombi/HDrezka-downloader#5]
Не знаю насколько это возможно реализовать в данном расширении, но было бы прекрасно иметь возможность скачивать фильм или сериал сразу с несколькими озвучками (а также субтитрами), чтобы была возможность между ними переключаться, выбирая другую аудио дорожку, а не скачивать отдельно для каждой озвучки заново целый фильм или сериал. Сейчас на сайте при выборе озвучки страница не перезагружается, а адрес ссылки не меняется, возможно можно как-то выбрать несколько озвучек, ещё на этом этапе...

**Comment by SuperZombi** [comment]
Можно реализовать, но тогда (как мне кажется) будет слишком перегруженый интерфейс.
Так что если накидаете варианты куда бы можно было добавить такую кнопку, то почему бы и нет.

И второе уточнение, фильмы идут сразу со звуком (нельзя отдельно скачать видео, а отдельно аудио дорожку).
