### ISSUE TITLE
Добавьте, пожалуйста, расширения в веб-магазин Chrome

### ISSUE THREAD

**Issue by RedebMar** [SuperZombi/HDrezka-downloader#6]
И, если можете, добавьте, пжлст, расширения в веб-магазин chrome.

**Comment by SuperZombi** [comment]
Этого не могу. Там нужно покупать "аккаунт разработчика" (своего рода защита от всякого мусора).
Хоть она и не дорого стоит, но это по сути покупка в никуда, которая не окупиться, так что я свои деньги тратить не хочу.

**Comment by SuperZombi** [comment]
Также, если не секрет, @RedebMar, скажите, пожалуйста, откуда вы узнали про моё расширение?

**Comment by SuperZombi** [comment]
Добавил
