### ISSUE TITLE
Добавить поддержку закачки субтитров вмести с фильмом

### ISSUE THREAD

**Issue by RomanBiluy** [SuperZombi/HDrezka-downloader#7]
Вы не могли б добавить поддержку закачки субтитров вмести с фильмом (или также в зависимости выбрана, то есть включена эта опция в самом плеере, по принципу, как сейчас, сделан выбор озвучки для скачивания, ну или добавить такую опцию в меню расширение, чтоб тот кому это не нужно мог отключить) так ка это, например, сделано в плагине hdrezka.tv к KODI (https://github.com/dandygithub/kodi) как раз оттуда и узнал о вашем расширении, ну или в приложение HDRezka App на андроиде, а то некоторые фильмы или сериалы просто невозможно смотреть без субтитров. Спасибо.

**Comment by SuperZombi** [comment]
Субтитры не знаю как получить из плеера

**Comment by SergiiKuzminov** [comment]
> Субтитры не знаю как получить из плеера

Підтримую. Круто було б, якщо можна й відразу скачати субтитри, особливо форсовані, які досить важко відшукати окремо. Також використовую плагін резкі в KODI і там субтитри підтягуються автоматично, значить апі резкі дозволяє їх завантажувати. Тим не менш, вдячний вам за прекрасне розширення.

**Comment by SuperZombi** [comment]
Добавил функцию скачивания субтитров.
Если вы имели ввиду встроить субтитры в само видео, то это не возможно в реализации плагина. Для этого нужен ffmpeg.
(Скачать)[https://github.com/SuperZombi/HDrezka-downloader/releases/tag/3.1.0]
