### ISSUE TITLE
Не скачивается в FHD

### ISSUE THREAD

**Issue by leofisun** [SuperZombi/HDrezka-downloader#9]
Заметил, что сейчас с HDRezka невозможно скачать контент в Full HD (1080p и 1080p Ultra) качестве каким-либо образом. 
С данным расширением, к сожалению, то же самое :(

Будет ли фикс с добавлением возможности скачивания в высоком качестве?

**Comment by SuperZombi** [comment]
Что именно у вас не скачивается? У меня все качает.
Возможно вы имеете в виду, что 1080 и 1080 Ultra имеют одинаковый размер (т.е. один и тот же файл). Это означает, что резка не имеет просто-напросто выше расширения в своей базе (в самом плеере там то же самое).

**Comment by leofisun** [comment]
Хотелось бы, но попробуйте сами скачать одну серию, к примеру, сериала "Элементарно" 2012 года. Даунлоадер даёт возможность скачать, но на выходе по неизвестной причине получается лишь 720p. 

До этого скачивал другим софтом, но сейчас и им не получается: выходит только 720p и всё. Другим софтом получилось вытянуть "Стартап" 2016 года в Full HD; всё прекрасно работало.

**Comment by SuperZombi** [comment]
![image](https://user-images.githubusercontent.com/75096786/181959057-5ef32d9f-b9d3-4e85-8e5d-e4dc93f32608.png)

**Comment by SuperZombi** [comment]
@leofisun, Посмотрите доступно ли у вас в плеере 1080. И если нет, то попробуйте с другого зеркала сайта. Ну это явно проблемы не с расширением.

**Comment by leofisun** [comment]
> @leofisun, Посмотрите доступно ли у вас в плеере 1080. И если нет, то попробуйте с другого зеркала сайта. Ну это явно проблемы не с расширением.

Да, в плеере доступно. Только заметил, что некоторые сериалы грузятся без проблем ("И снова здравствуйте!"), но те, о которых я писал выше ("Элементарно", "Династия"), на выходе показывают лишь 720p. 

Прикладываю скриншоты:

<img width="717" alt="Снимок экрана 2022-07-31 в 18 15 13" src="https://user-images.githubusercontent.com/54034988/182033225-d36db874-7611-45c5-bfbc-5d63457dc754.png">
<img width="1012" alt="Снимок экрана 2022-07-31 в 18 17 52" src="https://user-images.githubusercontent.com/54034988/182033230-cc885fc7-fae9-4b17-ad6f-7402faef35a6.png">

**Comment by SuperZombi** [comment]
Ну значит у резки проблемы. Либо у тебя.
